### PR TITLE
escape quotes and newlines on jedi command line and strip carriage returns

### PR DESCRIPTION
**Pull request by swryan**
Hi.. I made these changes to get the plugin to work on Windows, also checks out on OSX

Need to write some test specs, but you're welcome to take & try this out in the meantime...

### CODE REVIEW

**Comment by fallenhitokiri** [comment]
Awesome, thank you!

This branch[1] will go into master and be published tomorrow (hopefully) - it moves from running a Python process on every keystroke to a permanently running daemon. This should also take care of the problems this PR fixes.

If the branch is delayed for whatever reason I'll merge and publish it as it is right now, tested in a Windows 7 VM and is working.

[1] https://github.com/fallenhitokiri/autocomplete-plus-jedi/tree/daemon

**Comment by swryan** [comment]
sounds like a great improvement... will be interested to try it

**Comment by fallenhitokiri** [comment]
0.0.8 was just published introducing the completion daemon.

**Comment by swryan** [comment]
0.0.8 looks to be working great.. much faster...  no need for these changes anymore  ;)

**Pull request closed without merging**
